---

  extends: airbnb

  parser: babel-eslint

  settings:

    # import-resolver
    import/resolver:
      webpack: { config: 'webpack.config.js' }

  rules:

    semi: [2, never]
    indent: [2, tab]

    no-script-url: 0
    no-confusing-arrow: 0
    func-names: 0

    # react
    react/prop-types: 0
    react/jsx-closing-bracket-location: 0
    react/jsx-first-prop-new-line: 0
    react/jsx-indent-props: [2, tab]
    react/jsx-indent: [2, tab]
