---

  extends: airbnb

  parser: babel-eslint

  rules:

    semi: [2, never]
    indent: [2, tab]

    no-script-url: 0
    no-confusing-arrow: 0
    func-names: 0

    # react
    react/prop-types: 0
    react/jsx-closing-bracket-location: 0
    react/jsx-indent-props: [2, tab]
